services:
  database: 
    image: mongo:latest
    container_name: mdb-salero-beach
    ports:
      - "27018:27017"
    volumes:
      - ./data/db:/data/db

  api_rest: 
    build: ./backend
    container_name: backend-salero-beach 
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - MONGO_URI=mongodb://database:27017/salero_beach

  web-app: 
    build: ./frontend
    container_name: react-salero-beach
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app          
      - /app/node_modules
    depends_on:
      - api_rest