services:
  api_rest: 
    build: ./backend
    container_name: backend-salero-beach 
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://emaxss05:promopush_2023@cluster0.pdg5oqs.mongodb.net/salero_beach?appName=Cluster0
      - JWT_SECRET=salerobeach_secret_2024
    volumes:
      - ./backend/uploads:/app/uploads

  web-app: 
    build: ./frontend
    container_name: react-salero-beach
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app          
      - /app/node_modules
    depends_on:
      - api_rest